import { Commendation, DepartmentName, MilitaryRank, MonthlyReportEvaluation, Reprimand, Reward, Soldier } from '../types';

export const MILITARY_RANKS: { category: string; ranks: MilitaryRank[] }[] = [
  {
    category: 'Sĩ quan',
    ranks: [
      'Đại tá',
      'Thượng tá',
      'Trung tá',
      'Thiếu tá',
      'Đại úy',
      'Thượng úy',
      'Trung úy',
      'Thiếu úy',
    ],
  },
  {
    category: 'Quân nhân chuyên nghiệp',
    ranks: [
      'Thượng tá QNCN',
      'Trung tá QNCN',
      'Thiếu tá QNCN',
      'Đại úy QNCN',
      'Thượng úy QNCN',
      'Trung úy QNCN',
      'Thiếu úy QNCN',
    ],
  },
  {
    category: 'Hạ sĩ quan - Binh sĩ',
    ranks: ['Thượng sĩ', 'Trung sĩ', 'Hạ sĩ', 'Binh nhất', 'Binh nhì'],
  },
];

export const DEPARTMENTS: DepartmentName[] = [
  'Ban Chỉ huy Đồn',
  'Đội Vũ trang',
  'Đội Vận động quần chúng',
  'Đội Phòng chống ma túy và tội phạm',
  'Đội Kiểm soát hành chính',
  'Đội Trinh sát',
  'Trạm Kiểm soát Biên phòng Bãi Nhà',
  'Trạm Kiểm soát Biên phòng Bãi Bấc',
  'Bộ phận Hậu cần - Kỹ thuật',
  'Bộ phận Thông tin - Cơ yếu',
];

export const COMMON_POSITIONS = [
  'Đồn trưởng',
  'Chính trị viên',
  'Phó Đồn trưởng quân sự',
  'Chính trị viên phó',
  'Đội trưởng Đội Vũ trang',
  'Phó Đội trưởng Đội Vũ trang',
  'Đội trưởng Đội Vận động quần chúng',
  'Phó Đội trưởng Đội Vận động quần chúng',
  'Đội trưởng Đội PC Ma túy & Tội phạm',
  'Đội trưởng Đội Kiểm soát hành chính',
  'Đội trưởng Đội Trinh sát',
  'Trạm trưởng Trạm KSBĐ Bãi Nhà',
  'Trạm phó Trạm KSBĐ Bãi Nhà',
  'Trạm trưởng Trạm KSBĐ Bãi Bấc',
  'Nhân viên Vận động quần chúng',
  'Nhân viên Kiểm soát hành chính',
  'Nhân viên Trinh sát',
  'Nhân viên Hậu cần',
  'Nhân viên Quân y',
  'Nhân viên Cơ yếu - Thông tin',
  'Thuyền trưởng tàu tuần tra',
  'Tiểu đội trưởng',
  'Chiến sĩ',
];

export const COMMENDATION_TEMPLATES = [
  {
    title: 'Trách nhiệm cao trong thực hiện nhiệm vụ',
    content:
      'Có tinh thần trách nhiệm cao trong thực hiện nhiệm vụ, tích cực tham gia xây dựng đơn vị, hoàn thành tốt nhiệm vụ được giao.',
    achievement: 'Gương mẫu, chấp hành nghiêm điều lệnh, đóng góp tích cực vào phong trào thi đua quyết thắng.',
  },
  {
    title: 'Tuần tra kiểm soát bảo vệ vững chắc địa bàn biển đảo',
    content:
      'Chủ động khắc phục khó khăn sóng gió, tổ chức tuần tra kiểm soát chặt chẽ khu vực biển và bờ đảo Hòn Sơn, đảm bảo an toàn tuyệt đối.',
    achievement: 'Phát hiện, nhắc nhở và ngăn chặn kịp thời các phương tiện tàu cá vi phạm ranh giới và quy định IUU.',
  },
  {
    title: 'Tận tụy giúp đỡ nhân dân phòng chống thiên tai',
    content:
      'Tích cực tham gia hỗ trợ ngư dân chằng chống tàu thuyền, chằng néo nhà cửa tránh bão, củng cố vững chắc tình đoàn kết quân dân.',
    achievement: 'Cứu hộ thành công ngư dân bị trôi dạt trên biển, được chính quyền và nhân dân xã đảo khen ngợi.',
  },
  {
    title: 'Thành tích trong công tác vận động quần chúng',
    content:
      'Tuyên truyền sâu rộng Luật Biên phòng Việt Nam và chống khai thác IUU cho ngư dân địa phương, tạo chuyển biến rõ nét trong nhận thức của bà con.',
    achievement: 'Vận động 100% chủ phương tiện tàu cá tại địa bàn ký cam kết không vi phạm vùng biển nước ngoài.',
  },
  {
    title: 'Duy trì nghiêm chế độ canh trực, sẵn sàng chiến đấu',
    content:
      'Chấp hành nghiêm chế độ trực chỉ huy, trực ban, trực chiến và canh gác; xử lý linh hoạt, đúng đối sách các tình huống trên biển.',
    achievement: 'Bảo đảm an toàn tuyệt đối cơ quan, vũ khí trang bị và vùng biển quản lý.',
  },
];

export const REPRIMAND_TEMPLATES = [
  {
    title: 'Chấp hành lễ tiết tác phong chưa nghiêm',
    content:
      'Mang mặc trang phục chưa đúng điều lệnh trong giờ hành chính, xưng hô chào hỏi chưa đúng quy định của quân đội.',
    defectCause: 'Ý thức rèn luyện cá nhân chưa cao, còn chủ quan.',
    remediationPlan:
      'Nghiêm túc tự kiểm điểm, chấn chỉnh ngay lễ tiết tác phong, chấp hành nghiêm quy định mang mặc của Quân đội và BĐBP.',
  },
  {
    title: 'Chậm trễ trong chấp hành giờ giấc giao ban, điểm danh',
    content:
      'Có mặt muộn trong buổi giao ban tuần của đơn vị mà không có lý do chính đáng báo cáo chỉ huy.',
    defectCause: 'Tác phong chậm chạp, sắp xếp thời gian chưa khoa học.',
    remediationPlan:
      'Rút kinh nghiệm sâu sắc, đảm bảo giờ nào việc nấy, không để tái phạm làm ảnh hưởng đến tính chính quy của đơn vị.',
  },
  {
    title: 'Vệ sinh nội vụ phòng ở chưa gọn gàng',
    content:
      'Chăn màn xếp chưa vuông góc, dụng cụ cá nhân sắp đặt chưa đúng trật tự nội vụ vệ sinh trong doanh trại.',
    defectCause: 'Còn thói quen cẩu thả trong sinh hoạt hằng ngày.',
    remediationPlan:
      'Khắc phục sắp xếp nội vụ ngăn nắp theo đúng quy định điều lệnh quản lý bộ đội trước 17h00 cùng ngày.',
  },
  {
    title: 'Ghi chép sổ sách tuần tra kiểm soát chưa đầy đủ',
    content:
      'Nhật ký kiểm soát phương tiện ra vào bến còn thiếu một số thông tin thuyền viên và số đăng ký tàu.',
    defectCause: 'Chưa tập trung cao độ trong ca trực, làm việc qua loa.',
    remediationPlan:
      'Bổ sung hoàn thiện hồ sơ kiểm soát, kiểm tra đối chiếu kỹ lưỡng 100% phương tiện cập cảng.',
  },
];

export const INITIAL_SOLDIERS: Soldier[] = [
  {
    id: 's-1',
    stt: 1,
    fullName: 'Võ Thanh Vàng',
    rank: 'Trung tá',
    position: 'Đồn trưởng',
    department: 'Ban Chỉ huy Đồn',
    birthDate: '1982-05-14',
    status: 'Đang công tác',
    notes: 'Chỉ huy chung mọi mặt công tác tại Đồn BP Hòn Sơn',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-2',
    stt: 2,
    fullName: 'Nguyễn Nguyên Bá',
    rank: 'Trung tá',
    position: 'Chính trị viên',
    department: 'Ban Chỉ huy Đồn',
    birthDate: '1983-09-20',
    status: 'Đang công tác',
    notes: 'Phụ trách công tác Đảng, công tác chính trị',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-3',
    stt: 3,
    fullName: 'Nguyễn Quốc Tuấn',
    rank: 'Thiếu tá',
    position: 'Phó Đồn trưởng quân sự',
    department: 'Ban Chỉ huy Đồn',
    birthDate: '1987-11-12',
    status: 'Đang công tác',
    notes: 'Phụ trách công tác sẵn sàng chiến đấu, tuần tra biển',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-4',
    stt: 4,
    fullName: 'Phạm Minh Đức',
    rank: 'Đại úy',
    position: 'Chính trị viên phó',
    department: 'Ban Chỉ huy Đồn',
    birthDate: '1990-03-08',
    status: 'Đang công tác',
    notes: 'Phụ trách thanh niên, thi đua khen thưởng',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-5',
    stt: 5,
    fullName: 'Vũ Đình Trọng',
    rank: 'Đại úy',
    position: 'Đội trưởng Đội Vũ trang',
    department: 'Đội Vũ trang',
    birthDate: '1991-07-22',
    status: 'Đang công tác',
    notes: 'Chỉ huy tuần tra kiểm soát trên biển và ven đảo',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-6',
    stt: 6,
    fullName: 'Bùi Thanh Tùng',
    rank: 'Thượng úy',
    position: 'Đội trưởng Đội Vận động quần chúng',
    department: 'Đội Vận động quần chúng',
    birthDate: '1993-12-05',
    status: 'Đang công tác',
    notes: 'Phụ trách địa bàn dân cư xã Lại Sơn (Hòn Sơn)',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-7',
    stt: 7,
    fullName: 'Hoàng Hải Đăng',
    rank: 'Thượng úy',
    position: 'Đội trưởng Đội Kiểm soát hành chính',
    department: 'Đội Kiểm soát hành chính',
    birthDate: '1994-04-18',
    status: 'Đang công tác',
    notes: 'Kiểm soát phương tiện tàu bè cập bến Hòn Sơn',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-8',
    stt: 8,
    fullName: 'Đỗ Hữu Nghĩa',
    rank: 'Đại úy',
    position: 'Trạm trưởng Trạm KSBĐ Bãi Nhà',
    department: 'Trạm Kiểm soát Biên phòng Bãi Nhà',
    birthDate: '1990-10-30',
    status: 'Đang công tác',
    notes: 'Quản lý cửa ngõ chính cảng Bãi Nhà',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-9',
    stt: 9,
    fullName: 'Ngô Văn Kiên',
    rank: 'Thượng úy',
    position: 'Trạm trưởng Trạm KSBĐ Bãi Bấc',
    department: 'Trạm Kiểm soát Biên phòng Bãi Bấc',
    birthDate: '1993-02-14',
    status: 'Đang công tác',
    notes: 'Trực trạm phía bắc đảo',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-10',
    stt: 10,
    fullName: 'Trần Đăng Khoa',
    rank: 'Trung úy QNCN',
    position: 'Thuyền trưởng tàu tuần tra',
    department: 'Đội Vũ trang',
    birthDate: '1996-08-19',
    status: 'Đang công tác',
    notes: 'Vận hành tàu cao tốc tuần tra BP',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-11',
    stt: 11,
    fullName: 'Nguyễn Tấn Đạt',
    rank: 'Trung úy',
    position: 'Nhân viên Vận động quần chúng',
    department: 'Đội Vận động quần chúng',
    birthDate: '1997-06-25',
    status: 'Đang công tác',
    notes: 'Gắn bó thường xuyên với ngư dân và trường học trên đảo',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-12',
    stt: 12,
    fullName: 'Lê Văn Hiếu',
    rank: 'Thiếu úy QNCN',
    position: 'Nhân viên Quân y',
    department: 'Bộ phận Hậu cần - Kỹ thuật',
    birthDate: '1998-01-10',
    status: 'Đang công tác',
    notes: 'Chăm sóc sức khỏe bộ đội và sơ cấp cứu ngư dân',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-13',
    stt: 13,
    fullName: 'Đặng Quốc Huy',
    rank: 'Thượng sĩ',
    position: 'Tiểu đội trưởng',
    department: 'Đội Vũ trang',
    birthDate: '2004-03-15',
    status: 'Đang công tác',
    notes: 'Quản lý khẩu đội canh trực',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-14',
    stt: 14,
    fullName: 'Phan Bảo Long',
    rank: 'Trung sĩ',
    position: 'Chiến sĩ trinh sát',
    department: 'Đội Trinh sát',
    birthDate: '2005-09-02',
    status: 'Đang công tác',
    notes: 'Nắm tình hình an ninh trật tự địa bàn',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-15',
    stt: 15,
    fullName: 'Võ Minh Nhật',
    rank: 'Hạ sĩ',
    position: 'Chiến sĩ',
    department: 'Trạm Kiểm soát Biên phòng Bãi Nhà',
    birthDate: '2005-11-20',
    status: 'Đang công tác',
    notes: 'Trực gác cổng và kiểm tra vé tàu cao tốc',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's-16',
    stt: 16,
    fullName: 'Huỳnh Gia Bảo',
    rank: 'Binh nhất',
    position: 'Chiến sĩ',
    department: 'Đội Vũ trang',
    birthDate: '2006-02-17',
    status: 'Đang công tác',
    notes: 'Tích cực tham gia tăng gia sản xuất và thể thao',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
];

export const INITIAL_COMMENDATIONS: Commendation[] = [
  {
    id: 'com-1',
    soldierId: 's-6',
    fullName: 'Bùi Thanh Tùng',
    rank: 'Thượng úy',
    position: 'Đội trưởng Đội Vận động quần chúng',
    department: 'Đội Vận động quần chúng',
    date: '2026-09-04',
    weekNumber: 1,
    month: 9,
    year: 2026,
    content:
      'Chủ động phối hợp UBND xã Lại Sơn tổ chức tuyên truyền chống khai thác IUU cho hơn 120 chủ tàu cá và thuyền trưởng trên đảo Hòn Sơn.',
    achievement: '100% chủ tàu cá cam kết bật thiết bị giám sát hành trình VMS 24/24 khi ra khơi.',
    proposedBy: 'Lê Hoàng Nam - Chính trị viên',
    commendationType: 'Biểu dương trong giao ban tuần',
    notes: 'Gương mẫu trong công tác dân vận',
    createdAt: '2026-09-04T10:00:00Z',
  },
  {
    id: 'com-2',
    soldierId: 's-10',
    fullName: 'Trần Đăng Khoa',
    rank: 'Trung úy QNCN',
    position: 'Thuyền trưởng tàu tuần tra',
    department: 'Đội Vũ trang',
    date: '2026-09-05',
    weekNumber: 1,
    month: 9,
    year: 2026,
    content:
      'Vận hành tàu tuần tra vượt sóng gió cấp 5, tiếp cận và lai dắt an toàn một phương tiện tàu câu mực của ngư dân bị hỏng máy trôi dạt vào bãi đá ngầm.',
    achievement: 'Cứu hộ kịp thời 03 ngư dân và tài sản giá trị hơn 500 triệu đồng.',
    proposedBy: 'Vũ Đình Trọng - Đội trưởng Đội Vũ trang',
    commendationType: 'Biểu dương trước toàn đồn',
    notes: 'Hành động dũng cảm cứu dân trên biển',
    createdAt: '2026-09-05T14:30:00Z',
  },
  {
    id: 'com-3',
    soldierId: 's-12',
    fullName: 'Lê Văn Hiếu',
    rank: 'Thiếu úy QNCN',
    position: 'Nhân viên Quân y',
    department: 'Bộ phận Hậu cần - Kỹ thuật',
    date: '2026-09-11',
    weekNumber: 2,
    month: 9,
    year: 2026,
    content:
      'Kịp thời cấp cứu và truyền dịch ổn định sức khỏe cho một du khách lớn tuổi bị tai biến nhẹ tại bến tàu Bãi Nhà trong điều kiện thời tiết biển động chưa thể chuyển viện vào đất liền.',
    achievement: 'Xử lý y tế chuyên môn chuẩn xác, trách nhiệm cao, được nhân dân cảm kích.',
    proposedBy: 'Đỗ Hữu Nghĩa - Trạm trưởng Bãi Nhà',
    commendationType: 'Biểu dương trong giao ban tuần',
    notes: 'Quân y tận tụy vì sức khỏe nhân dân',
    createdAt: '2026-09-11T16:00:00Z',
  },
  {
    id: 'com-4',
    soldierId: 's-5',
    fullName: 'Vũ Đình Trọng',
    rank: 'Đại úy',
    position: 'Đội trưởng Đội Vũ trang',
    department: 'Đội Vũ trang',
    date: '2026-09-12',
    weekNumber: 2,
    month: 9,
    year: 2026,
    content:
      'Chỉ huy kíp tuần tra đêm phát hiện và ngăn chặn 01 ghe cào vi phạm quy định khai thác hải sản tận diệt gần bờ khu vực biển Hòn Rái.',
    achievement: 'Bảo vệ nguồn lợi thủy sản ven đảo và giữ nghiêm kỷ cương pháp luật vùng biển.',
    proposedBy: 'Nguyễn Quốc Tuấn - Phó Đồn trưởng QS',
    commendationType: 'Biểu dương trước toàn đồn',
    notes: 'Khen thưởng chuyên môn',
    createdAt: '2026-09-12T09:15:00Z',
  },
  {
    id: 'com-5',
    soldierId: 's-16',
    fullName: 'Huỳnh Gia Bảo',
    rank: 'Binh nhất',
    position: 'Chiến sĩ',
    department: 'Đội Vũ trang',
    date: '2026-09-18',
    weekNumber: 3,
    month: 9,
    year: 2026,
    content:
      'Có tinh thần trách nhiệm cao trong thực hiện nhiệm vụ canh gác đài quan sát, tích cực tham gia tăng gia sản xuất, hoàn thành xuất sắc chỉ tiêu rau xanh và thịt sạch cho bếp ăn đơn vị.',
    achievement: 'Gương mẫu, tích cực xây dựng cảnh quan doanh trại chính quy xanh - sạch - đẹp.',
    proposedBy: 'Vũ Đình Trọng - Đội trưởng Đội Vũ trang',
    commendationType: 'Biểu dương trên bảng tin thi đua',
    notes: 'Chiến sĩ trẻ tiêu biểu',
    createdAt: '2026-09-18T11:00:00Z',
  },
  {
    id: 'com-6',
    soldierId: 's-10',
    fullName: 'Trần Đăng Khoa',
    rank: 'Trung úy QNCN',
    position: 'Thuyền trưởng tàu tuần tra',
    department: 'Đội Vũ trang',
    date: '2026-09-23',
    weekNumber: 4,
    month: 9,
    year: 2026,
    content:
      'Bảo dưỡng vũ khí trang bị kỹ thuật và máy chính tàu tuần tra hoạt động ổn định, tiết kiệm nhiên liệu, sẵn sàng cơ động thực hiện nhiệm vụ 24/24.',
    achievement: 'Hệ số kỹ thuật của phương tiện đạt 100%, bảo đảm cơ động an toàn trong mọi thời tiết.',
    proposedBy: 'Nguyễn Quốc Tuấn - Phó Đồn trưởng QS',
    commendationType: 'Biểu dương trong giao ban tuần',
    notes: 'Thợ máy - thuyền trưởng giỏi',
    createdAt: '2026-09-23T15:00:00Z',
  },
  {
    id: 'com-7',
    soldierId: 's-8',
    fullName: 'Đỗ Hữu Nghĩa',
    rank: 'Đại úy',
    position: 'Trạm trưởng Trạm KSBĐ Bãi Nhà',
    department: 'Trạm Kiểm soát Biên phòng Bãi Nhà',
    date: '2026-09-26',
    weekNumber: 4,
    month: 9,
    year: 2026,
    content:
      'Chỉ đạo kiểm soát chặt chẽ 100% lượt tàu khách cao tốc từ Rạch Giá ra đảo Hòn Sơn trong dịp cuối tuần, thái độ văn minh, lịch sự, đúng điều lệnh.',
    achievement: 'Tạo hình ảnh đẹp về người chiến sĩ Biên phòng trong lòng du khách và bà con nhân dân.',
    proposedBy: 'Trần Văn Mạnh - Đồn trưởng',
    commendationType: 'Biểu dương trong giao ban tuần',
    notes: 'Chính quy cửa khẩu cảng',
    createdAt: '2026-09-26T17:30:00Z',
  },
];

export const INITIAL_REPRIMANDS: Reprimand[] = [
  {
    id: 'rep-1',
    soldierId: 's-15',
    fullName: 'Võ Minh Nhật',
    rank: 'Hạ sĩ',
    position: 'Chiến sĩ',
    department: 'Trạm Kiểm soát Biên phòng Bãi Nhà',
    date: '2026-09-08',
    weekNumber: 2,
    month: 9,
    year: 2026,
    content:
      'Chấp hành lễ tiết tác phong chưa nghiêm túc, mang mặc trang phục chưa đúng điều lệnh khi làm nhiệm vụ hướng dẫn du khách tại cầu cảng Bãi Nhà.',
    defectCause: 'Ý thức rèn luyện cá nhân chưa cao, chưa tập trung trong ca trực.',
    reprimandType: 'Nhắc nhở tại giao ban tuần',
    remediationPlan:
      'Nghiêm túc tự kiểm điểm trước tổ công tác, chỉnh đốn trang phục chuẩn quy định điều lệnh Quân đội.',
    reviewedBy: 'Đỗ Hữu Nghĩa - Trạm trưởng Bãi Nhà',
    remediationStatus: 'Đã khắc phục sửa chữa',
    notes: 'Đã chấp hành tốt sau nhắc nhở',
    createdAt: '2026-09-08T09:00:00Z',
  },
  {
    id: 'rep-2',
    soldierId: 's-13',
    fullName: 'Đặng Quốc Huy',
    rank: 'Thượng sĩ',
    position: 'Tiểu đội trưởng',
    department: 'Đội Vũ trang',
    date: '2026-09-16',
    weekNumber: 3,
    month: 9,
    year: 2026,
    content:
      'Chậm trễ 15 phút trong buổi tập trung kiểm tra thể lực buổi sáng của đơn vị, chưa làm gương cho chiến sĩ cấp dưới.',
    defectCause: 'Chưa chủ động sắp xếp thời gian biểu cá nhân.',
    reprimandType: 'Nhắc nhở tại giao ban tuần',
    remediationPlan:
      'Rút kinh nghiệm sâu sắc, nêu cao tính gương mẫu của Tiểu đội trưởng, bảo đảm đúng giờ giấc theo hiệu lệnh.',
    reviewedBy: 'Vũ Đình Trọng - Đội trưởng Đội Vũ trang',
    remediationStatus: 'Đang chuyển biến tốt',
    notes: 'Cần duy trì nghiêm kỷ luật',
    createdAt: '2026-09-16T11:00:00Z',
  },
];

export const INITIAL_REWARDS: Reward[] = [
  {
    id: 'rew-1',
    soldierId: 's-10',
    fullName: 'Trần Đăng Khoa',
    rank: 'Trung úy QNCN',
    position: 'Thuyền trưởng tàu tuần tra',
    department: 'Đội Vũ trang',
    rewardType: 'Giấy khen Bộ Chỉ huy BĐBP Tỉnh Kiên Giang',
    achievement:
      'Có thành tích xuất sắc trong công tác tìm kiếm cứu hộ, cứu nạn ngư dân trên vùng biển Kiên Hải năm 2026.',
    decisionNumber: '118/QĐ-KT',
    decisionDate: '2026-07-28',
    decisionLevel: 'Bộ Chỉ huy Bộ đội Biên phòng Tỉnh Kiên Giang',
    year: 2026,
    month: 7,
    notes: 'Khen thưởng đột xuất',
    createdAt: '2026-07-28T09:00:00Z',
  },
  {
    id: 'rew-2',
    soldierId: 's-6',
    fullName: 'Bùi Thanh Tùng',
    rank: 'Thượng úy',
    position: 'Đội trưởng Đội Vận động quần chúng',
    department: 'Đội Vận động quần chúng',
    rewardType: 'Chiến sĩ thi đua cơ sở',
    achievement:
      'Đạt danh hiệu Chiến sĩ thi đua cơ sở, hoàn thành xuất sắc nhiệm vụ công tác vận động quần chúng và xây dựng thế trận biên phòng toàn dân vững mạnh.',
    decisionNumber: '254/QĐ-BCH',
    decisionDate: '2026-01-15',
    decisionLevel: 'Bộ Chỉ huy Bộ đội Biên phòng Tỉnh Kiên Giang',
    year: 2026,
    month: 1,
    notes: 'Khen thưởng tổng kết phong trào TĐQT',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'rew-3',
    soldierId: 's-2',
    fullName: 'Lê Hoàng Nam',
    rank: 'Trung tá',
    position: 'Chính trị viên',
    department: 'Ban Chỉ huy Đồn',
    rewardType: 'Bằng khen Bộ Tư lệnh Bộ đội Biên phòng',
    achievement:
      'Có thành tích xuất sắc trong lãnh đạo, chỉ đạo công tác Đảng, công tác chính trị và phong trào Toàn dân tham gia bảo vệ chủ quyền lãnh thổ, an ninh biên giới quốc gia.',
    decisionNumber: '89/QĐ-BTL',
    decisionDate: '2026-03-03',
    decisionLevel: 'Bộ Tư lệnh Bộ đội Biên phòng',
    year: 2026,
    month: 3,
    notes: 'Kỷ niệm ngày truyền thống BĐBP',
    createdAt: '2026-03-03T10:00:00Z',
  },
];

export const INITIAL_EVALUATION: MonthlyReportEvaluation = {
  id: 'eval_2026_9',
  month: 9,
  year: 2026,
  generalReview:
    'Trong tháng 9/2026, tình hình chủ quyền vùng biển, an ninh trật tự trên địa bàn xã đảo Hòn Sơn cơ bản ổn định. Đơn vị duy trì nghiêm các chế độ trực sẵn sàng chiến đấu, tuần tra kiểm soát trên biển và địa bàn ven đảo.',
  advantages:
    '- 100% cán bộ, chiến sĩ an tâm tư tưởng, chấp hành nghiêm kỷ luật Quân đội, pháp luật Nhà nước và điều lệnh Biên phòng.\n- Các đội, trạm phối hợp chặt chẽ, hoàn thành tốt nhiệm vụ kiểm soát tàu cá chống khai thác IUU và cứu hộ ngư dân trên biển.\n- Công tác biểu dương thi đua tuần được duy trì nề nếp, kịp thời khích lệ tinh thần cán bộ chiến sĩ hoàn thành tốt nhiệm vụ.',
  disadvantages:
    '- Còn cá biệt một số trường hợp hạ sĩ quan, chiến sĩ trẻ mang mặc lễ tiết tác phong chưa thật chuẩn mực trong ca trực, thời gian tập trung có lúc chưa kịp thời đã được chỉ huy nhắc nhở chấn chỉnh ngay.',
  solutions:
    '- Tiếp tục duy trì nghiêm chế độ canh trực sẵn sàng chiến đấu 24/24.\n- Tăng cường kiểm tra lễ tiết tác phong, điều lệnh quản lý bộ đội.\n- Đẩy mạnh công tác tuyên truyền phòng chống IUU cho ngư dân mùa mưa bão.\n- Kịp thời phát hiện và biểu dương nhân rộng các gương điển hình tiên tiến trong tuần và tháng.',
  reporterName: 'Phạm Minh Đức',
  reporterPosition: 'Chính trị viên phó',
  commanderName: 'Lê Hoàng Nam',
  commanderPosition: 'Chính trị viên Đồn Biên phòng Hòn Sơn',
  updatedAt: '2026-09-30T08:00:00Z',
};

export const LEAVE_CATEGORIES = ['Đi phép', 'Tranh thủ'] as const;

export const LEAVE_TYPES_BY_CATEGORY: Record<string, string[]> = {
  'Đi phép': [
    'Phép năm',
    'Phép đặc biệt',
    'Phép việc riêng',
    'Phép bù trực bão / trực SSCĐ',
    'Phép thi / học tập nâng cao',
  ],
  'Tranh thủ': [
    'Tranh thủ cuối tuần',
    'Tranh thủ giải quyết việc gia đình',
    'Tranh thủ 24 giờ',
    'Tranh thủ 48 giờ',
    'Tranh thủ trong ngày',
  ],
};

export const INITIAL_LEAVES = [
  {
    id: 'leave-1',
    soldierId: 's-13',
    fullName: 'Nguyễn Văn Hùng',
    rank: 'Đại úy QNCN',
    position: 'Nhân viên Hậu cần',
    department: 'Bộ phận Hậu cần - Kỹ thuật',
    category: 'Đi phép' as const,
    leaveType: 'Phép năm',
    startDate: '2026-09-20',
    endDate: '2026-10-01',
    daysCount: 12,
    destination: 'TP. Rạch Giá, tỉnh Kiên Giang',
    reason: 'Nghỉ phép năm định kỳ theo chế độ tiêu chuẩn sĩ quan, QNCN',
    approver: 'Trung tá Trần Đình Trọng - Đồn trưởng',
    licenseNumber: 'GP-18/ĐBP',
    status: 'Đang nghỉ' as const,
    notes: 'Đã bàn giao công tác quân nhu, giữ liên lạc điện thoại hàng ngày',
    createdAt: '2026-09-19T08:00:00Z',
  },
  {
    id: 'leave-2',
    soldierId: 's-9',
    fullName: 'Võ Hoàng Long',
    rank: 'Thượng úy',
    position: 'Đội trưởng',
    department: 'Đội Trinh sát',
    category: 'Đi phép' as const,
    leaveType: 'Phép đặc biệt',
    startDate: '2026-09-28',
    endDate: '2026-10-02',
    daysCount: 5,
    destination: 'Huyện An Minh, tỉnh Kiên Giang',
    reason: 'Gia đình có việc hiếu (ông nội mất)',
    approver: 'Trung tá Lê Hoàng Nam - Chính trị viên',
    licenseNumber: 'GP-21/ĐBP',
    status: 'Đang nghỉ' as const,
    notes: 'Bàn giao nhiệm vụ phụ trách trinh sát cho đồng chí Phó Đội trưởng',
    createdAt: '2026-09-27T14:30:00Z',
  },
  {
    id: 'leave-3',
    soldierId: 's-17',
    fullName: 'Bùi Văn Hậu',
    rank: 'Trung sĩ',
    position: 'Tiểu đội trưởng',
    department: 'Đội Vũ trang',
    category: 'Tranh thủ' as const,
    leaveType: 'Tranh thủ cuối tuần',
    startDate: '2026-09-26',
    endDate: '2026-09-27',
    daysCount: 2,
    destination: 'Ấp Bãi Nhà, xã Lại Sơn, Kiên Hải',
    reason: 'Thăm thân nhân gia đình sinh sống trên đảo Hòn Sơn',
    approver: 'Thiếu tá Hoàng Quốc Việt - Phó Đồn trưởng',
    licenseNumber: 'TT-09/ĐBP',
    actualReturnDate: '2026-09-27',
    status: 'Đã về đơn vị' as const,
    notes: 'Về đơn vị đúng 17h00 ngày 27/09, chấp hành tốt kỷ luật',
    createdAt: '2026-09-25T16:00:00Z',
  },
  {
    id: 'leave-4',
    soldierId: 's-19',
    fullName: 'Đỗ Văn Thành',
    rank: 'Binh nhất',
    position: 'Chiến sĩ',
    department: 'Trạm Kiểm soát Biên phòng Bãi Nhà',
    category: 'Tranh thủ' as const,
    leaveType: 'Tranh thủ giải quyết việc gia đình',
    startDate: '2026-09-12',
    endDate: '2026-09-14',
    daysCount: 2,
    destination: 'Xã đảo Hòn Tre, Kiên Hải',
    reason: 'Gia đình có người nhà nhập viện',
    approver: 'Trung tá Lê Hoàng Nam - Chính trị viên',
    licenseNumber: 'TT-05/ĐBP',
    actualReturnDate: '2026-09-14',
    status: 'Đã về đơn vị' as const,
    notes: 'Đã về đơn vị an toàn, báo cáo trực ban tác chiến đúng giờ',
    createdAt: '2026-09-11T10:00:00Z',
  },
];

