import mammoth from 'mammoth';
import {
  AlignmentType,
  BorderStyle,
  Document,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import { DepartmentName, DutyStatus, MilitaryRank, Soldier } from '../types';
import { DEPARTMENTS } from '../constants/ranksAndDepartments';

export interface ParsedSoldierCandidate {
  stt?: number;
  fullName: string;
  rank: MilitaryRank;
  position: string;
  department: DepartmentName;
  birthDate?: string;
  status?: DutyStatus;
  notes?: string;
  phoneNumber?: string;
}

// Helper: Normalize header string to detect column types
function detectColumnType(headerText: string): string {
  const norm = headerText.toLowerCase().trim().replace(/[\s_.-]+/g, ' ');
  if (/^(stt|số tt|số thứ tự|no|index)$/.test(norm)) return 'stt';
  if (/cấp bậc|bậc|quân hàm|rank/.test(norm)) return 'rank';
  if (/họ và tên|họ tên|họ và chữ lót|tên|full name|name/.test(norm)) return 'fullName';
  if (/chức vụ|vị trí|chức danh|position|role/.test(norm)) return 'position';
  if (/đội|trạm|bộ phận|đơn vị|phòng ban|department|unit/.test(norm)) return 'department';
  if (/ngày sinh|năm sinh|sinh ngày|ngày tháng năm sinh|dob|birth/.test(norm)) return 'birthDate';
  if (/trạng thái|tình trạng|công tác|duty|status/.test(norm)) return 'status';
  if (/số điện thoại|sđt|điện thoại|phone/.test(norm)) return 'phoneNumber';
  if (/ghi chú|chú thích|note|remark/.test(norm)) return 'notes';
  return 'unknown';
}

// Clean and normalize text
function cleanText(txt: string): string {
  return txt.replace(/\s+/g, ' ').trim();
}

// Standardize rank
function normalizeRank(raw: string): MilitaryRank {
  const c = cleanText(raw);
  if (!c) return 'Binh nhì';
  return c;
}

// Standardize department
function normalizeDepartment(raw: string): DepartmentName {
  const c = cleanText(raw);
  if (!c) return 'Ban Chỉ huy Đồn';
  // Try to find matching department from standard list
  const match = DEPARTMENTS.find(
    (d) => d.toLowerCase() === c.toLowerCase() || c.toLowerCase().includes(d.toLowerCase())
  );
  if (match) return match;
  return c;
}

// Parse HTML generated by mammoth from .docx file
export function parseHtmlTableFromWord(html: string): ParsedSoldierCandidate[] {
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const tables = doc.querySelectorAll('table');

  const candidates: ParsedSoldierCandidate[] = [];

  if (tables.length > 0) {
    tables.forEach((table) => {
      const rows = Array.from(table.querySelectorAll('tr'));
      if (rows.length < 2) return;

      // Identify header row
      let headerColMap: Record<number, string> = {};
      let headerRowIndex = 0;

      // Scan first 3 rows to find header
      for (let r = 0; r < Math.min(3, rows.length); r++) {
        const cells = Array.from(rows[r].querySelectorAll('th, td')).map((c) =>
          cleanText(c.textContent || '')
        );
        const recognized = cells.map(detectColumnType);
        const hasKeyFields = recognized.includes('fullName') || recognized.includes('rank') || recognized.includes('position');
        if (hasKeyFields) {
          headerRowIndex = r;
          recognized.forEach((type, idx) => {
            if (type !== 'unknown') headerColMap[idx] = type;
          });
          break;
        }
      }

      // If no recognized headers, fallback to default order: STT, Cấp bậc, Họ tên, Chức vụ, Đội/Trạm, Ngày sinh...
      if (Object.keys(headerColMap).length === 0) {
        headerColMap = {
          0: 'stt',
          1: 'rank',
          2: 'fullName',
          3: 'position',
          4: 'department',
          5: 'birthDate',
          6: 'status',
          7: 'notes',
        };
        headerRowIndex = 0; // if first row is not actual data, user will review
      }

      // Process data rows
      for (let r = headerRowIndex + 1; r < rows.length; r++) {
        const cells = Array.from(rows[r].querySelectorAll('td, th')).map((c) =>
          cleanText(c.textContent || '')
        );
        if (cells.every((c) => !c)) continue; // skip empty rows

        const item: Partial<ParsedSoldierCandidate> = {};
        cells.forEach((val, idx) => {
          const colType = headerColMap[idx];
          if (!colType || !val) return;
          if (colType === 'stt') {
            const num = parseInt(val, 10);
            if (!isNaN(num)) item.stt = num;
          } else if (colType === 'fullName') {
            item.fullName = val;
          } else if (colType === 'rank') {
            item.rank = normalizeRank(val);
          } else if (colType === 'position') {
            item.position = val;
          } else if (colType === 'department') {
            item.department = normalizeDepartment(val);
          } else if (colType === 'birthDate') {
            item.birthDate = val;
          } else if (colType === 'status') {
            item.status = val;
          } else if (colType === 'phoneNumber') {
            item.phoneNumber = val;
          } else if (colType === 'notes') {
            item.notes = val;
          }
        });

        if (item.fullName) {
          candidates.push({
            stt: item.stt || candidates.length + 1,
            fullName: item.fullName,
            rank: item.rank || 'Trung úy',
            position: item.position || 'Nhân viên',
            department: item.department || 'Đội Vũ trang',
            birthDate: item.birthDate || '1995-01-01',
            status: item.status || 'Đang công tác',
            notes: item.notes || '',
            phoneNumber: item.phoneNumber || '',
          });
        }
      }
    });
  }

  // If no tables found or empty, try parsing paragraph lines
  if (candidates.length === 0) {
    const paragraphs = Array.from(doc.querySelectorAll('p'))
      .map((p) => cleanText(p.textContent || ''))
      .filter(Boolean);
    return parseTextLines(paragraphs.join('\n'));
  }

  return candidates;
}

// Parse text lines (e.g. from copy/paste from Word, Excel, or plain text)
export function parseTextLines(text: string): ParsedSoldierCandidate[] {
  const lines = text
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);
  const candidates: ParsedSoldierCandidate[] = [];

  if (lines.length === 0) return candidates;

  // Check if first line is a header
  let startIndex = 0;
  const firstLineDelim = lines[0].includes('\t')
    ? '\t'
    : lines[0].includes(';')
    ? ';'
    : lines[0].includes('|')
    ? '|'
    : ',';

  const firstParts = lines[0].split(firstLineDelim).map(cleanText);
  const detectedTypes = firstParts.map(detectColumnType);
  let headerMap: Record<number, string> = {};

  if (detectedTypes.includes('fullName') || detectedTypes.includes('rank')) {
    startIndex = 1;
    detectedTypes.forEach((t, i) => {
      if (t !== 'unknown') headerMap[i] = t;
    });
  } else {
    // Default column mapping if tab-delimited
    headerMap = {
      0: 'stt',
      1: 'rank',
      2: 'fullName',
      3: 'position',
      4: 'department',
      5: 'birthDate',
      6: 'status',
      7: 'notes',
    };
  }

  for (let i = startIndex; i < lines.length; i++) {
    const line = lines[i];
    // Split by tab, pipe, semicolon, or comma
    const delim = line.includes('\t')
      ? '\t'
      : line.includes('|')
      ? '|'
      : line.includes(';')
      ? ';'
      : ',';

    const parts = line.split(delim).map(cleanText);

    // If only 1 part, see if it has dash separation like "1. Đại tá Nguyễn Văn A - Đồn trưởng - Ban Chỉ huy Đồn"
    if (parts.length === 1 && line.includes('-')) {
      const dashParts = line.split('-').map(cleanText);
      if (dashParts.length >= 2) {
        const namePart = dashParts[0].replace(/^\d+[\.\s\)]+/, '').trim();
        const posPart = dashParts[1] || 'Nhân viên';
        const deptPart = dashParts[2] || 'Đội Vũ trang';
        candidates.push({
          stt: candidates.length + 1,
          fullName: namePart,
          rank: 'Đại úy',
          position: posPart,
          department: normalizeDepartment(deptPart),
          birthDate: '1995-01-01',
          status: 'Đang công tác',
        });
        continue;
      }
    }

    if (parts.length >= 2) {
      const item: Partial<ParsedSoldierCandidate> = {};
      parts.forEach((val, idx) => {
        const col = headerMap[idx];
        if (!col || !val) return;
        if (col === 'stt') {
          const num = parseInt(val, 10);
          if (!isNaN(num)) item.stt = num;
        } else if (col === 'fullName') {
          item.fullName = val;
        } else if (col === 'rank') {
          item.rank = normalizeRank(val);
        } else if (col === 'position') {
          item.position = val;
        } else if (col === 'department') {
          item.department = normalizeDepartment(val);
        } else if (col === 'birthDate') {
          item.birthDate = val;
        } else if (col === 'status') {
          item.status = val;
        } else if (col === 'phoneNumber') {
          item.phoneNumber = val;
        } else if (col === 'notes') {
          item.notes = val;
        }
      });

      // If fullName wasn't populated from mapped headers, try heuristic
      if (!item.fullName) {
        // Find longest string that doesn't look like number or rank
        const nameCandidate = parts.find(
          (p) => isNaN(Number(p)) && p.length > 3 && !DEPARTMENTS.includes(p)
        );
        if (nameCandidate) item.fullName = nameCandidate;
      }

      if (item.fullName) {
        candidates.push({
          stt: item.stt || candidates.length + 1,
          fullName: item.fullName,
          rank: item.rank || 'Trung úy',
          position: item.position || 'Nhân viên',
          department: item.department || 'Đội Vũ trang',
          birthDate: item.birthDate || '1995-01-01',
          status: item.status || 'Đang công tác',
          notes: item.notes || '',
          phoneNumber: item.phoneNumber || '',
        });
      }
    }
  }

  return candidates;
}

// Parse JSON data (either array of objects or object with soldiers property)
export function parseSoldiersFromJson(jsonString: string): ParsedSoldierCandidate[] {
  const parsed = JSON.parse(jsonString);
  let rawList: any[] = [];

  if (Array.isArray(parsed)) {
    rawList = parsed;
  } else if (parsed && Array.isArray(parsed.soldiers)) {
    rawList = parsed.soldiers;
  } else if (parsed && typeof parsed === 'object') {
    // Check if any property is an array
    const firstArrayProp = Object.values(parsed).find((val) => Array.isArray(val));
    if (firstArrayProp) rawList = firstArrayProp as any[];
  }

  const candidates: ParsedSoldierCandidate[] = [];

  rawList.forEach((obj, idx) => {
    if (!obj || typeof obj !== 'object') return;

    // Support both Vietnamese & English property names
    const fullName =
      obj.fullName ||
      obj['Họ và tên'] ||
      obj['Họ tên'] ||
      obj.name ||
      obj['Tên'] ||
      '';

    if (!fullName) return;

    const rank =
      obj.rank ||
      obj['Cấp bậc'] ||
      obj['Quân hàm'] ||
      'Trung úy';

    const position =
      obj.position ||
      obj['Chức vụ'] ||
      obj['Vị trí'] ||
      'Nhân viên';

    const department =
      obj.department ||
      obj['Đội/Trạm'] ||
      obj['Bộ phận'] ||
      obj['Đơn vị'] ||
      'Đội Vũ trang';

    const birthDate =
      obj.birthDate ||
      obj['Ngày sinh'] ||
      obj['Năm sinh'] ||
      '1995-01-01';

    const status =
      obj.status ||
      obj['Trạng thái'] ||
      obj['Tình trạng'] ||
      'Đang công tác';

    const notes = obj.notes || obj['Ghi chú'] || '';
    const phoneNumber = obj.phoneNumber || obj['Số điện thoại'] || '';
    const stt = obj.stt || obj['STT'] || idx + 1;

    candidates.push({
      stt: Number(stt) || idx + 1,
      fullName: cleanText(fullName),
      rank: normalizeRank(rank),
      position: cleanText(position),
      department: normalizeDepartment(department),
      birthDate: cleanText(birthDate),
      status: cleanText(status),
      notes: cleanText(notes),
      phoneNumber: cleanText(phoneNumber),
    });
  });

  return candidates;
}

// Parse Word .docx file (using mammoth convertToHtml)
export async function parseDocxFile(file: File): Promise<ParsedSoldierCandidate[]> {
  const arrayBuffer = await file.arrayBuffer();
  const result = await mammoth.convertToHtml({ arrayBuffer });
  const html = result.value;
  return parseHtmlTableFromWord(html);
}

// Generate sample JSON template for user download
export function generateSampleJsonTemplate(): string {
  const sample = [
    {
      stt: 1,
      fullName: 'Trần Đình Trọng',
      rank: 'Trung tá',
      position: 'Đồn trưởng',
      department: 'Ban Chỉ huy Đồn',
      birthDate: '1982-04-15',
      status: 'Đang công tác',
      notes: 'Phụ trách chung toàn Đồn',
    },
    {
      stt: 2,
      fullName: 'Lê Hoàng Nam',
      rank: 'Trung tá',
      position: 'Chính trị viên',
      department: 'Ban Chỉ huy Đồn',
      birthDate: '1983-08-22',
      status: 'Đang công tác',
      notes: 'Bí thư Đảng ủy Đồn',
    },
    {
      stt: 3,
      fullName: 'Nguyễn Văn Minh',
      rank: 'Đại úy',
      position: 'Đội trưởng',
      department: 'Đội Vũ trang',
      birthDate: '1989-11-10',
      status: 'Đang công tác',
      notes: '',
    },
    {
      stt: 4,
      fullName: 'Phạm Văn Thành',
      rank: 'Thượng úy',
      position: 'Trạm trưởng',
      department: 'Trạm Kiểm soát Biên phòng Bãi Nhà',
      birthDate: '1992-06-18',
      status: 'Đang công tác',
      notes: '',
    },
    {
      stt: 5,
      fullName: 'Bùi Văn Hậu',
      rank: 'Trung sĩ',
      position: 'Tiểu đội trưởng',
      department: 'Đội Vũ trang',
      birthDate: '2004-03-05',
      status: 'Đang công tác',
      notes: '',
    },
  ];

  return JSON.stringify(sample, null, 2);
}

// Generate real sample DOCX template using docx library
export async function generateSampleDocxTemplate(): Promise<Blob> {
  const font = 'Times New Roman';
  const cellBorderThin = {
    top: { style: BorderStyle.SINGLE, size: 4, color: '000000' },
    bottom: { style: BorderStyle.SINGLE, size: 4, color: '000000' },
    left: { style: BorderStyle.SINGLE, size: 4, color: '000000' },
    right: { style: BorderStyle.SINGLE, size: 4, color: '000000' },
  };

  const headers = [
    'STT',
    'Cấp bậc',
    'Họ và tên',
    'Chức vụ',
    'Đội / Trạm / Bộ phận',
    'Ngày sinh (YYYY-MM-DD)',
    'Trạng thái',
    'Ghi chú',
  ];

  const sampleRowsData = [
    ['1', 'Trung tá', 'Trần Đình Trọng', 'Đồn trưởng', 'Ban Chỉ huy Đồn', '1982-04-15', 'Đang công tác', 'Phụ trách chung'],
    ['2', 'Trung tá', 'Lê Hoàng Nam', 'Chính trị viên', 'Ban Chỉ huy Đồn', '1983-08-22', 'Đang công tác', 'Bí thư Đảng ủy'],
    ['3', 'Đại úy', 'Nguyễn Văn Minh', 'Đội trưởng', 'Đội Vũ trang', '1989-11-10', 'Đang công tác', ''],
    ['4', 'Thượng úy', 'Phạm Văn Thành', 'Trạm trưởng', 'Trạm Kiểm soát Biên phòng Bãi Nhà', '1992-06-18', 'Đang công tác', ''],
    ['5', 'Trung sĩ', 'Bùi Văn Hậu', 'Tiểu đội trưởng', 'Đội Vũ trang', '2004-03-05', 'Đang công tác', ''],
  ];

  const tableRows: TableRow[] = [
    new TableRow({
      tableHeader: true,
      children: headers.map(
        (h) =>
          new TableCell({
            borders: cellBorderThin,
            shading: { type: ShadingType.CLEAR, fill: 'E2E8F0' },
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ text: h, bold: true, font, size: 20 })],
              }),
            ],
          })
      ),
    }),
    ...sampleRowsData.map(
      (row) =>
        new TableRow({
          children: row.map(
            (val, idx) =>
              new TableCell({
                borders: cellBorderThin,
                children: [
                  new Paragraph({
                    alignment: idx === 0 || idx === 1 || idx === 5 || idx === 6 ? AlignmentType.CENTER : AlignmentType.LEFT,
                    children: [new TextRun({ text: val, font, size: 20 })],
                  }),
                ],
              })
          ),
        })
    ),
  ];

  const doc = new Document({
    sections: [
      {
        properties: {
          page: { margin: { top: 1134, bottom: 1134, left: 1417, right: 1134 } },
        },
        children: [
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: 'CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM', bold: true, font, size: 22 })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: 'Độc lập - Tự do - Hạnh phúc', bold: true, font, size: 24 })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 300 },
            children: [new TextRun({ text: '————————', bold: true, font, size: 16 })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
            children: [new TextRun({ text: 'DANH SÁCH QUÂN NHÂN ĐỒN BIÊN PHÒNG HÒN SƠN', bold: true, font, size: 26 })],
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: cellBorderThin,
            rows: tableRows,
          }),
        ],
      },
    ],
  });

  return await Packer.toBlob(doc);
}
